// <auto-generated />
using System;
using Biblioteca82.Data.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca82.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Biblioteca82.Models.Domain.RolEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("EsBorrado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Rol");

                    b.HasData(
                        new
                        {
                            Id = new Guid("070ed413-0adf-4f5c-bb9b-cf49fbe4fb6f"),
                            EsBorrado = false,
                            Nombre = "Admin"
                        });
                });

            modelBuilder.Entity("Biblioteca82.Models.Domain.UsuarioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("EsBorrado")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdRol")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdRol");

                    b.ToTable("Tbl_Usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a995251-8d3b-4518-b5f7-333774af5603"),
                            EsBorrado = false,
                            IdRol = new Guid("070ed413-0adf-4f5c-bb9b-cf49fbe4fb6f"),
                            Nombre = "Emmanuel",
                            Password = "password",
                            UserName = "Emmanuel_Rojas"
                        });
                });

            modelBuilder.Entity("Biblioteca82.Models.Domain.UsuarioEntity", b =>
                {
                    b.HasOne("Biblioteca82.Models.Domain.RolEntity", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Biblioteca82.Models.Domain.RolEntity", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
